export const DASHBOARD_HTML = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CunRadar 控制台</title><style>
:root{color-scheme:dark;--bg:#08111f;--panel:#111d2f;--line:#26364d;--text:#e8f0fb;--muted:#91a4bc;--accent:#45d6a8;--danger:#ff6b7a}*{box-sizing:border-box}body{margin:0;font:14px/1.5 ui-sans-serif,system-ui;background:radial-gradient(circle at 20% 0,#14304a 0,transparent 40%),var(--bg);color:var(--text)}main{max-width:1120px;margin:auto;padding:32px 20px 80px}header{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:24px}h1{font-size:28px;margin:0}.muted{color:var(--muted)}.actions{display:flex;gap:10px;flex-wrap:wrap}button,a.btn{border:1px solid var(--line);background:#182940;color:var(--text);padding:9px 14px;border-radius:10px;text-decoration:none;cursor:pointer}button.primary{background:var(--accent);color:#052218;border-color:transparent;font-weight:700}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{background:color-mix(in srgb,var(--panel) 94%,transparent);border:1px solid var(--line);border-radius:16px;padding:18px}.wide{grid-column:1/-1}h2{font-size:16px;margin:0 0 14px}.row{display:grid;grid-template-columns:1fr 1.4fr auto;gap:8px;margin:8px 0}input{width:100%;border:1px solid var(--line);background:#0a1626;color:var(--text);padding:9px 10px;border-radius:9px}.remove{color:var(--danger)}label.toggle{display:flex;gap:10px;align-items:center}label.toggle input{width:auto}.status{padding:10px 0;border-bottom:1px solid var(--line);display:flex;justify-content:space-between}.toast{position:fixed;right:20px;bottom:20px;background:#1b3047;border:1px solid var(--line);padding:12px 16px;border-radius:10px;display:none}@media(max-width:760px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}header{align-items:flex-start;flex-direction:column}.row{grid-template-columns:1fr}.row button{justify-self:start}}
</style></head><body><main><header><div><h1>📡 CunRadar 控制台</h1><div class="muted" id="repo">载入中…</div></div><div class="actions"><a class="btn" id="report" target="_blank">打开日报</a><button id="run" class="primary">立即生成日报</button><button id="save">保存配置</button></div></header><section class="grid">
<div class="card"><h2>🎬 YouTube</h2><div id="youtube"></div><button data-add="youtube">+ 添加频道</button></div>
<div class="card"><h2>📺 B站</h2><div id="bilibili"></div><button data-add="bilibili">+ 添加 UP 主</button></div>
<div class="card"><h2>📝 RSS / 博客</h2><div id="rss"></div><button data-add="rss">+ 添加订阅</button></div>
<div class="card"><h2>💻 GitHub 项目</h2><div id="github"></div><button data-add="github">+ 添加仓库</button></div>
<div class="card"><h2>🔥 GitHub Trending</h2><label class="toggle"><input id="trend-enabled" type="checkbox">启用每日热门项目</label><p><input id="trend-language" placeholder="语言，例如 python；空为全部"></p><p><input id="trend-limit" type="number" min="1" max="50" placeholder="数量"></p></div>
<div class="card"><h2>运行状态</h2><div id="runs" class="muted">载入中…</div></div>
</section></main><div class="toast" id="toast"></div><script>
const specs={youtube:['名称','channel_id'],bilibili:['名称','uid'],rss:['名称','url'],github:['名称','repo']};let config;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';setTimeout(()=>el.style.display='none',2400)}
function row(type,item={}){const [label,key]=specs[type];const el=document.createElement('div');el.className='row';el.innerHTML='<input data-key="name" placeholder="'+label+'"><input data-key="'+key+'" placeholder="'+key+'"><button class="remove">删除</button>';el.querySelector('[data-key=name]').value=item.name||'';el.querySelector('[data-key='+key+']').value=item[key]||'';el.querySelector('button').onclick=()=>el.remove();return el}
function render(){for(const type of Object.keys(specs)){const box=document.querySelector('#'+type);box.replaceChildren();for(const item of config[type]||[])box.append(row(type,item))}document.querySelector('#trend-enabled').checked=config.github_trending.enabled;document.querySelector('#trend-language').value=config.github_trending.language||'';document.querySelector('#trend-limit').value=config.github_trending.limit||5}
function collect(){const out={};for(const [type,[,key]] of Object.entries(specs)){out[type]=[...document.querySelectorAll('#'+type+' .row')].map(el=>({name:el.querySelector('[data-key=name]').value.trim(),[key]:el.querySelector('[data-key='+key+']').value.trim()})).filter(x=>x.name&&x[key])}out.github_trending={enabled:document.querySelector('#trend-enabled').checked,language:document.querySelector('#trend-language').value.trim(),limit:Number(document.querySelector('#trend-limit').value)||5};return out}
async function api(path,options){const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw new Error(data.error||'请求失败');return data}
async function loadRuns(){const box=document.querySelector('#runs');const runs=await api('/api/runs');box.replaceChildren();if(!runs.length){box.textContent='暂无运行记录';return}for(const run of runs){const item=document.createElement('div');item.className='status';const link=document.createElement('a');link.href=run.html_url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=new Date(run.created_at).toLocaleString();const state=document.createElement('span');state.textContent=run.conclusion||run.status;item.append(link,state);box.append(item)}}
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.add).append(row(b.dataset.add)));
document.querySelector('#save').onclick=async()=>{try{await api('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(collect())});toast('配置已保存')}catch(e){toast(e.message)}};
document.querySelector('#run').onclick=async()=>{try{await api('/api/run',{method:'POST'});toast('日报任务已进入队列');setTimeout(loadRuns,1800)}catch(e){toast(e.message)}};
Promise.all([api('/api/config'),api('/api/meta')]).then(([cfg,meta])=>{config=cfg;render();document.querySelector('#repo').textContent=meta.repo;document.querySelector('#report').href=meta.report_url;return loadRuns()}).catch(e=>toast(e.message));
</script></body></html>`;
